version: "3.7"

services:

  item-db:

    image: mongo:3

    volumes:

      - app-db:/data/db
      
    ports:
      - 27017:27017

  item-app:

    image: ghcr.io/bagus-k/item-app:v1

    container_name: item-app

    ports:

      - 80:80

    volumes:

      - ./:/app

volumes:

  app-db: